### ISSUE TITLE
Its not working on Atmega328p

### ISSUE THREAD

**Issue by GDokmetas** [aostanin/avr-hd44780#1]
I have editted header file but its not shown correctly

**Comment by aostanin** [comment]
I only tested this on the Teensy++ 2.0 (AT90USB1286). I don't have the display anymore so I can't test it on other chips.

Maybe try using the Arduino library (https://github.com/arduino-libraries/LiquidCrystal) which is still actively maintained.

**Comment by alex-3-30** [comment]
In my project (ATMega128A, internal osc. 8MHz) it's work only if I change delay in function lcd_write_nibble(). If value of this delay less than 0.3ms, display is don't ready to new command. And displayed not all symbols or noise.

**Comment by aostanin** [comment]
@alex-3-30 I don't have access to the hardware anymore so I can't test any changes but I'd be happy to accept any pull requests which fix your issue.

**Comment by aostanin** [comment]
Possibly fixed in #2. Closing for now.
