### ISSUE TITLE
lcd_create_char() not fully working

### ISSUE THREAD

**Issue by flexxxxer** [aostanin/avr-hd44780#5]
I needed to make the character of the letter Ё (yo, letter from russian language). I defined the symbol as follows:
```
uint8_t yo_character[8] = {
        0b01010,
        0b00000,
        0b01110,
        0b01000,
        0b01000,
        0b01110,
        0b01000,
        0b01110
};
```

Having studied the api, I realized that I need to use the `lcd_create_char()` method. After which I wrote the following:
```
lcd_create_char(0, yo_character);
lcd_write(0);
```
Naturally, I called methods `lcd_init()` and `lcd_on()` before the operations I described above.
I managed to solve the problem by typing, supplementing the code above as follows:
```
lcd_create_char(0, yo_character);
lcd_command(0x80); // but i don't know why it works 
lcd_write(0);
```
However, there is a clarification: the program was run on the hapsim emulator for atmega32. 

If this is a problem then it would be good to solve it. With respect :)

**Comment by aostanin** [comment]
Thank you for the bug report. Sadly, it's been years since I last used this library and I no longer have access to any hardware to verify if any changes work. I'd be happy to accept a pull request, though.
